Update org.standardnotes.standardnotes.metainfo.xml
flathub/org.standardnotes.standardnotes pull request #3
Opened 2021-02-18 16:28 UTC by baptiste-grob

Hey there! I'm Baptiste, and I work at Standard Notes.

It's nice to see you managed to build a flatpak of the app!

Unfortunately we're not in a position to maintain it at the moment. However, we know there are many people who would like to use the app as a flatpak, so this PR adds "(Unofficial)" to relevant description fields to avoid any confusion as to what they can expect in terms of support.

Thanks!

2021-03-06 14:17 UTC, proletarius101 commented on org.standardnotes.standardnotes.metainfo.xml
> +    <p><em>(Note: This release is built by a 3rd party from official Standard Notes releases. Standard Notes is
Sorry for the late response!

Please move this to the last line of the description, and rephrase it like `NOTE: This release is not verified by, affiliated with, or supported by Standard Notes Ltd.` which is a standard statement as appeared in https://flathub.org/apps/details/com.getpostman.Postman

https://flathub.org/apps/details/com.getpostman.Postman

2021-03-06 14:20 UTC, proletarius101 requested changes

2021-03-06 14:20 UTC, proletarius101 commented on org.standardnotes.standardnotes.metainfo.xml
> +  <name>Standard Notes (Unofficial)</name>
There is no app listed in flathub having an `unofficial` suffix. I think it's sufficient to have the statement in the description/summary.

2021-03-09 10:49 UTC, proletarius101 commented
Thanks!

2021-03-09 10:49 UTC, merged

2021-05-20 06:08 UTC, barthalion commented
Hey @baptiste-grob, I'm one of Flathub co-founders/administrators/infrastructure engineers. Just a heads-up that I decided to drop `(Unofficial)` from the summary (it's the short blurb visible under application name) as it's very not standard and just doesn't look well. However, I moved the "not affiliated" note to the top of the regular description so it should be better visible on the website and native frontends like GNOME Software. I hope that's fine with you.